<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-02-25 at 17:13:28.
 */
class TeaMakerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TeaMaker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TeaMaker;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TeaMaker::make
     * @todo   Implement testMake().
     */
    public function testMake() {
        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
        
        assert(true);
    }

}
